capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('ottanime.urls')),
    # all-auth url needed  for all authenticationBackend configurations
    path('', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
]

# These are used for storing user-uploaded files like images, videos, etc
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# this code is adding URL patterns for serving static and media files when the settings.DEBUG variable is True during development. 
# When the settings.DEBUG variable is False, these URL patterns will not be added, 
# this is helpful during deployment when the files are served by web server directly rather than by the web application.

ottanime/urls.py
from django.urls import path
from . views import *



# using as a namespace
app_name = 'ottanime'

#here are my views which show at the url secction
urlpatterns = [
    path("", Home.as_view(), name="Home"),
    path('accounts/profile/', ProfileList.as_view(), name="profile-list"),
    path('profiles/create/', ProfileCreate.as_view(), name="profile-create"),
    path('watch/<str:profile_id>/', MovieList.as_view(), name="movie-list"),
    path('watch/detail/<str:movie_id>/',
         MovieDetail.as_view(), name="movie-detail"),
    path('watch/play/<str:movie_id>/', PlayMovie.as_view(), name="play-movie"),
    path('logout/', logout_view, name='logout'),
]

ottanime/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

# Create your models here.

AGE_CHOICES = {
    ('All', 'All'),
    ('kids', 'kids'),
}

MOVIE_CHOICES = {
    # for code , for front end
    ('seasonal', 'Seasonal'),
    ('single', 'Single'),
}

# 1. helps us to create some users
class CustomUser(AbstractUser):
    profiles = models.ManyToManyField(
        'Profile', blank=True) 
        # many to many field is given so that user can have many profiles.
        # blank = true means that user can have blank profiles.

# 2. og class spec for profiles
class Profile(models.Model):
    name = models.CharField(max_length=1000)
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)
    # keep track of individual user id
    uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.name


# 3. class model spec for movies
class Movie(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    # auto now add is used for created time automatically
    created = models.DateTimeField(auto_now_add=True)
    # keep track of individual user id
    uuid = models.UUIDField(default=uuid.uuid4)
    # check if this has seasons or single movie
    type = models.CharField(choices=MOVIE_CHOICES, max_length=100)
    #add the video files many to many field is use becuase if it has multiple videos like seasons
    video = models.ManyToManyField('Video')
    # for adding cover or thumbnail images
    image = models.ImageField(upload_to="covers")
    # for adding the constraints for age 
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)

   # it only returns the movie name when calls
    def __str__(self):
        return self.title

# 4. class model for video player
class Video(models.Model):
    # for video title name
    title = models.CharField(max_length=1000)
    # for getting video form file
    file = models.FileField(upload_to='movies')

    # only return the title of the video
    def __str__(self):
        return self.title

ottanime/forms.py
from django.forms import ModelForm
from . models import Profile

class ProfileForm(ModelForm):
    class Meta:
        # adding profile from the model to the model
        model = Profile
        # excluding the uuid field
        exclude = ['uuid']

        # so in this we are asking every things form profile model but excluding uuid 

ottanime/views.py
from django.views import View
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# importing models and form .py files 
from . forms import *
from . models import *


class Home(View):
    def get(self, request, *args, **kwargs):
        # if user is authenticated than send him to create the profile page 
        if request.user.is_authenticated:
            return redirect('ottanime:profile-list')
        # otherwise send him to the index page
        return render(request, 'index.html')


# user need to be authenticated
method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self, request, *args, **kwargs):
        # it gets the logged in user (request.user) and all the user profiles
        profiles = request.user.profiles.all()
        # passing temp to context of profile list
        context = {
            'profiles': profiles
        }
        return render(request, 'profilelist.html', context)



method_decorator(login_required, name='dispatch')
class ProfileCreate(View):
    # get method decorator
    def get(self, request, *args, **kwargs):
        form = ProfileForm()
        context = {
            'form': form
        }
        return render(request, 'profilecreate.html', context)

    # post method decorator
    def post(self, request, *args, **kwargs):
        # request.post to get info that user has passed in post 
        form = ProfileForm(request.POST or None)
        #
        if form.is_valid():
            # creating the profile form if is_valid usr or info provided is in our constraints
            # **form.is_valid is used in place of user = user and name = name works the same way
            profile = Profile.objects.create(**form.cleaned_data)
            # checking if usr has profile
            if profile:
                # if user is logged then add this profile
                request.user.profiles.add(profile)
                return redirect('ottanime:profile-list')
        context = {
            'form': form
        }
        return render(request, 'profilecreate.html', context)


method_decorator(login_required, name='dispatch')
class MovieList(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            #getting obj of profile in profile of a particular user here uuid is profile_id
            profile = Profile.objects.get(uuid=profile_id)
            #getting the movies & filtering the movies with age limit
            movies = Movie.objects.filter(age_limit=profile.age_limit)
            # checkng the profile is logged in via the req usr
            if profile not in request.user.profiles.all():
                return redirect('ottanime:profile-list')
            context = {
                'movies': movies
            }
            return render(request, 'movielist.html', context)
        #if profile is not exist
        except Profile.DoesNotExist:
            return redirect('ottanime:profile-list')


#you can also use @login_required insted of method decorator to check login when you use def based view
method_decorator(login_required, name='dispatch')
class MovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            #getting movire acc. to uuid from request usr to movie_id
            movie = Movie.objects.get(uuid=movie_id)

            context = {
                'movie': movie
            }

            return render(request, 'moviedetail.html', context)
        except Movie.DoesNotExist:
            return redirect('ottanime:profile-list')


method_decorator(login_required, name='dispatch')
class PlayMovie(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            movie = movie.video.values()

            context = {
                'movie': list(movie)#because we have more than one movie
            }

            return render(request, 'playmovie.html', context)
        except Movie.DoesNotExist:
            return redirect('ottanime:profile-list')


def logout_view(request):
    logout(request)
    return redirect('login')

templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Unlimited movies, TV shows, and more.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Watch anywhere. Cancel anytime.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Ready to watch? Enter your email to create or restart your membership.
        </h4>

        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <input type="email" name="" id="" placeholder="Email address" class="md:py-5 py-4 px-2 placeholder-gray-500 rounded-tl-sm rounded-bl-sm outline-none  text-gray-900 bg-gray-50 block w-8/12 md:w-3/4">
                <button class="bg-primary_red font-medium md:font-normal md:w-1/4 flex justify-center items-center py-4 px-1 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl">
                    <span>
                        Get Started
                    </span>
                    <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                </button>
            </div>
        </div>
    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center order-2'>
        <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>
    
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
    </div>
</section>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OttAnime</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</head>
<body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'images/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>
        <div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Logout
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </a>
            {% endif %}
        </div>
    </nav>
    {% block body %}

    {% endblock%}
     <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; All Right Reserved | 2022</li>
            <li> Netflix Clone</li>
            <li>By: Harshit Mishra ~ auscode</li>
        </ul>
    </footer> 
</body>
</html>

templates/moviedetail.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover " 
        style="background-image: url('{{ movie.image.url }}');">
            <div>
                <label class="text-6xl font-semibold text-white my-4 black-blur" style="font-weight: bolder;">
                    {{ movie.title }}
                </h2></label>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4 black-blur">{{movie.description}}</p>
                <div class="flex my-4">
                    <a href="{% url 'ottanime:play-movie' movie_id=movie.uuid %}" class="flex items-center py-2 px-4 rounded-md" 
                        style="background-color: #f44336">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">Play</span>
                    </a>                
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative " >
                <h2 class="text-gray-200 text-3xl font-medium">Description</h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">{{movie.description}}</p>
                </div>
            </div>
        </section>
    </main>
    <script>
        const nav = document.querySelector('nav')
        document.addEventListener("scroll",e=>{
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
            }else{
                nav.classList.remove('bg-gray-900')
            }
        })
    </script>
{% endblock %}

templates/movielist.html
{% extends 'layout.html' %} 
{% load static %} 

{% block body %}
<main class="bg-primary_black min-h-screen w-full">
  <section
    class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover"
    style="background-image: url('{% static 'images/dbz-dark.jpg' %}')">
    <div>
      <h2 class="text-6xl font-semibold text-white my-4">Dragon Ball Super</h2>
      <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
        Dragon Ball Super (Japanese: ドラゴンボール超スーパー, Hepburn: Doragon
        Bōru Sūpā, sometimes abbreviated as DBS) is a Japanese manga series
        written by Akira Toriyama and illustrated by Toyotarou. A sequel to
        Toriyama's original Dragon Ball manga, it follows the adventures of Goku
        and friends during the ten-year timeskip after the defeat of Majin
        Buu.It began serialization in Shueisha's monthly shōnen manga magazine V
        Jump in June 2015. The manga is simulpublished in English by Viz Media
        and by Shueisha on their Manga Plus platform.</p>
      <div class="flex my-4">
        <button class="flex items-center py-2 px-4 rounded-md"style="background-color: #f44336">
          <ion-icon name="play" class="text-2xl"></ion-icon>
          <span class="ml-3 font-medium"> Play </span>
        </button>
        <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-4 rounded-md">
          <ion-icon name="information-circle-outline" class="text-2xl"></ion-icon>
          <span class="ml-3 font-medium"> More Info </span>
        </button>
      </div>
    </div>
  </section>
  <section class="bg-primary_black min-h-screen flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Popular on Ottanime</h2>
      <div class="flex justify-center items-center min-w-full movie_lis">
        {% for movie in movies %}
        <a href="{% url 'ottanime:movie-detail' movie_id=movie.uuid %}">
          <div class="h-40 m-4 bg-blue-500 flex-shrink-0 rounded-md cursor-pointer w-40">
            <img src="{{movie.image.url}}" class="w-full h-full" alt="" />
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </section>
</main>
{% endblock %}

templates/playmovie.html
{% extends 'layout.html' %} {% load static %} {% block body %}
<main class="bg-primary_black h-full w-full">
  {% comment %} The json_script filter is used to convert the movie variable
  into a JSON object and create a script element with an id of 'movie_data'
  {%endcomment %} {{movie|json_script:'movie_data'}}
  <video controls class="w-full h-screen player"></video>
  {% comment %} This script element contains the JSON representation of the
  movie variable and can be accessed by JavaScript to retrieve data about the
  movie. {% endcomment %}
</main>
{% comment %} javascript {% endcomment %}
<script>
  
  {% comment %} selecting video query  {% endcomment %}
  const videoEl = document.querySelector('video')

  {% comment %} This method convert the json string into javascript object and the object is assigned to variable movie_data {% endcomment %}
  const movie_data = JSON.parse(document.getElementById('movie_data').textContent);

  {% comment %} location.href property is used to get the entire URL of the current web page, which is then 
  passed as an argument to the URL constructor. {% endcomment %}
  const url = new URL(location.href)

  {% comment %} This retrieves the value of the query parameter "epi"OR UUID from the current URL, parse it as integer and assigns it to 
  the variable named video_param. {% endcomment %}
  const video_param = parseInt(url.searchParams.get('epi'))?parseInt(url.searchParams.get('epi')):0

  {% comment %} This line of code sets the src attribute of the videoEl element to a 
  specific URL constructed from a string and movie_data[video_param].file and assigns it to the src attribute of the video element, 
  allowing the video to be played by loading it from the specified URL. {% endcomment %}
  videoEl.setAttribute('src', `http://localhost:8000/media/${movie_data[video_param].file}`)
  
</script>
{% comment %} In this way, the code can be used to play a video based on the query parameter passed in the URL and data of the movie. {% endcomment %}


{% endblock %}

templates/profilecreate.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">
                {% csrf_token %}
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100" type="submit">Create Profile</button>
                </div>
            </form> 
        </div>
    </section>
{% endblock %}

templates/profilelist.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center' 
        style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
            {% comment %} loop for adding multiple LOC of profiles  {% endcomment %}
            {% for profile in profiles %}
            {% if forloop.counter <= 5 %}
            <a href="{% url 'ottanime:movie-list' profile_id=profile.uuid %}">
                <div class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex">
                    <p class="text-6xl" style="font-weight: 900;">
                        {% comment %} slicing to 1letter from user name initials only {% endcomment %}
                        {{profile.name|slice:":1"}}</p>
                    <p>{{profile.name}}</p>
                </div>
            </a>
            {% endif %}
            {% endfor %}
            
        </div>
        {% comment %} creating another profile  {% endcomment %}
        <div class="flex justify-center items-center">
            <a href="{% url 'ottanime:profile-create' %}" class="px-4 py-2 rounded-md outline-none text-gray-100" 
                style="background-color: #0F3460;">
                Add A New Profile
            </a>
        </div>
    </section>

{% endblock %}